# Generated by Django 5.1.6 on 2025-03-10 17:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('destination_address', models.TextField()),
                ('current_status', models.CharField(choices=[('Package Created', 'Package Created'), ('Dispatched', 'Dispatched'), ('Arrived at Local storage', 'Arrived at Local Storage'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Pending', max_length=50)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('ordered_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('shipped_date', models.DateTimeField(auto_now_add=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_status', models.CharField(choices=[('Package Created', 'Package Created'), ('Dispatched', 'Dispatched'), ('Arrived at Local storage', 'Arrived at Local Storage'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], max_length=50)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('tracking_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='app_shipment.shipment')),
            ],
        ),
    ]
